//! Device identity keys that stay inside Rust.
//!
//! A device's long-term signing key (ML-DSA-87 + Ed25519) authenticates it to
//! the server, and its share decapsulation key opens everything other users have
//! shared with it. Both used to be handed to the app as base64 in a JVM/Swift
//! `String` — immutable, possibly interned, never zeroized, and therefore still
//! readable in a heap dump or crash report long after use (audit C-1).
//!
//! Here the key material is created, used and destroyed on this side of the FFI.
//! Callers get an opaque [`IdentityHandle`] plus the *public* halves, ask this
//! module to sign or to open a share, and persist only a [`DeviceIdentity::seal`]
//! blob they cannot read. The only bytes that cross the boundary are a 32-byte
//! sealing key — a byte array both sides can wipe, unlike a string.

use std::collections::HashMap;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Mutex;

use rand_core::{OsRng, RngCore};
use zeroize::Zeroizing;

use crate::error::{Result, VelaError};
use crate::{aead, kem, signing};

/// Version byte on the sealed blob, so the format can change without ambiguity.
const SEALED_VERSION: u8 = 1;

/// The public halves — safe to store in the clear and to send to the server.
#[derive(Debug, Clone, PartialEq)]
pub struct IdentityPublics {
    /// Hybrid KEM public key registered as this device's identity.
    pub hybrid_ek: Vec<u8>,
    /// Hybrid signing verification key the server checks auth signatures with.
    pub hybrid_vk: Vec<u8>,
    /// Hybrid KEM public key other users seal shares to.
    pub share_ek: Vec<u8>,
}

/// A device's private keys. Never serialized except through [`seal`](Self::seal).
pub struct DeviceIdentity {
    signing_sk: signing::HybridSigningKey,
    share_dk: kem::HybridSecretKey,
    publics: IdentityPublics,
}

impl std::fmt::Debug for DeviceIdentity {
    /// Never print key material — `VaultItem`'s derived `Debug` leaking secrets
    /// is a known footgun in this codebase; do not add another.
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("DeviceIdentity([REDACTED])")
    }
}

impl DeviceIdentity {
    /// Generate a fresh identity: signing keypair, share keypair, and the KEM
    /// public key that identifies the device to the server.
    pub fn generate() -> Result<Self> {
        let (hybrid_vk, signing_sk) = signing::generate_keypair()?;
        let (share_ek, share_dk) = kem::generate_keypair();
        // The matching secret for `hybrid_ek` is deliberately dropped: nothing
        // in the protocol encapsulates under it, it exists so the device has a
        // real KEM public key to register rather than filler bytes.
        let (hybrid_ek, _unused_dk) = kem::generate_keypair();

        Ok(Self {
            signing_sk,
            share_dk,
            publics: IdentityPublics {
                hybrid_ek: hybrid_ek.to_bytes(),
                hybrid_vk: hybrid_vk.to_bytes().to_vec(),
                share_ek: share_ek.to_bytes(),
            },
        })
    }

    /// Adopt key material that already exists elsewhere.
    ///
    /// Two callers need this and neither can be avoided: migrating a device that
    /// stored its keys in the clear before this module existed, and enrollment,
    /// where the signing key is generated by the enrolling device and travels in
    /// the enrollment code. Both hand the bytes over exactly once; from then on
    /// the keys live here.
    pub fn import(
        signing_sk: &[u8],
        share_dk: Option<&[u8]>,
        hybrid_ek: Option<&[u8]>,
    ) -> Result<Self> {
        let signing_sk = signing::HybridSigningKey::from_bytes(signing_sk)?;
        let hybrid_vk = signing_sk.verifying_key();

        let (share_ek, share_dk) = match share_dk {
            Some(bytes) => {
                let dk = kem::HybridSecretKey::from_bytes(bytes)?;
                let ek = dk.public_key();
                (ek.to_bytes(), dk)
            }
            None => {
                let (ek, dk) = kem::generate_keypair();
                (ek.to_bytes(), dk)
            }
        };

        let hybrid_ek = match hybrid_ek {
            Some(bytes) => bytes.to_vec(),
            None => kem::generate_keypair().0.to_bytes(),
        };

        Ok(Self {
            signing_sk,
            share_dk,
            publics: IdentityPublics {
                hybrid_ek,
                hybrid_vk: hybrid_vk.to_bytes().to_vec(),
                share_ek,
            },
        })
    }

    pub fn publics(&self) -> &IdentityPublics {
        &self.publics
    }

    /// Replace the share keypair, e.g. when the account never registered one.
    /// Returns the new public half; the caller must re-seal and publish it.
    pub fn rotate_share_key(&mut self) -> Vec<u8> {
        let (ek, dk) = kem::generate_keypair();
        self.share_dk = dk;
        self.publics.share_ek = ek.to_bytes();
        self.publics.share_ek.clone()
    }

    /// Sign a server auth challenge, binding it to `device_id`.
    pub fn sign_auth(&self, device_id: &str, challenge: &[u8]) -> Result<Vec<u8>> {
        let message = signing::auth_message(device_id, challenge);
        Ok(signing::sign(&self.signing_sk, &message)?.to_bytes().to_vec())
    }

    /// Open a capsule another user sealed to this device's share key.
    pub fn open_share(&self, capsule: &[u8]) -> Result<Vec<u8>> {
        kem::open_share(&self.share_dk, capsule)
    }

    /// Encrypt the private halves under `key` for the app to persist.
    ///
    /// The app stores an opaque blob: it can lose it, but it cannot read a key
    /// out of it, and nothing it holds is a string containing one.
    pub fn seal(&self, key: &[u8; 32]) -> Result<Vec<u8>> {
        let signing_bytes = Zeroizing::new(self.signing_sk.to_bytes());
        let share_bytes = Zeroizing::new(self.share_dk.to_bytes());

        let mut plaintext = Zeroizing::new(Vec::with_capacity(
            1 + 12 + signing_bytes.len() + share_bytes.len() + self.publics.hybrid_ek.len(),
        ));
        plaintext.push(SEALED_VERSION);
        push_field(&mut plaintext, &signing_bytes);
        push_field(&mut plaintext, &share_bytes);
        push_field(&mut plaintext, &self.publics.hybrid_ek);

        aead::encrypt(key, &plaintext)
    }

    /// Recover an identity from [`seal`](Self::seal).
    pub fn open(sealed: &[u8], key: &[u8; 32]) -> Result<Self> {
        let plaintext = Zeroizing::new(aead::decrypt(key, sealed)?.to_vec());
        let mut rest: &[u8] = &plaintext;

        let version = take_byte(&mut rest)?;
        if version != SEALED_VERSION {
            return Err(VelaError::InvalidParameter(format!(
                "unsupported sealed identity version {version}"
            )));
        }
        let signing_sk = Zeroizing::new(take_field(&mut rest)?);
        let share_dk = Zeroizing::new(take_field(&mut rest)?);
        let hybrid_ek = take_field(&mut rest)?;

        Self::import(&signing_sk, Some(&share_dk), Some(&hybrid_ek))
    }
}

fn push_field(out: &mut Vec<u8>, field: &[u8]) {
    out.extend_from_slice(&(field.len() as u32).to_be_bytes());
    out.extend_from_slice(field);
}

fn take_byte(rest: &mut &[u8]) -> Result<u8> {
    let (first, tail) = rest
        .split_first()
        .ok_or_else(|| VelaError::InvalidParameter("sealed identity is truncated".into()))?;
    *rest = tail;
    Ok(*first)
}

fn take_field(rest: &mut &[u8]) -> Result<Vec<u8>> {
    if rest.len() < 4 {
        return Err(VelaError::InvalidParameter(
            "sealed identity is truncated".into(),
        ));
    }
    let (len_bytes, tail) = rest.split_at(4);
    let len = u32::from_be_bytes(len_bytes.try_into().expect("4 bytes")) as usize;
    if tail.len() < len {
        return Err(VelaError::InvalidParameter(
            "sealed identity is truncated".into(),
        ));
    }
    let (field, tail) = tail.split_at(len);
    *rest = tail;
    Ok(field.to_vec())
}

// ── Handles ─────────────────────────────────────────────────────────────────

/// An opaque reference an app can hold instead of a key.
pub type IdentityHandle = u64;

static NEXT_HANDLE: AtomicU64 = AtomicU64::new(1);
static IDENTITIES: Mutex<Option<HashMap<IdentityHandle, DeviceIdentity>>> = Mutex::new(None);

fn with_registry<T>(f: impl FnOnce(&mut HashMap<IdentityHandle, DeviceIdentity>) -> T) -> T {
    let mut guard = IDENTITIES.lock().unwrap_or_else(|e| e.into_inner());
    f(guard.get_or_insert_with(HashMap::new))
}

/// Take ownership of `identity` and return the handle that stands for it.
pub fn register(identity: DeviceIdentity) -> IdentityHandle {
    // Handles are sequential, not secret: they never leave the process, and a
    // caller that can guess one can already call the FFI directly.
    let handle = NEXT_HANDLE.fetch_add(1, Ordering::SeqCst);
    with_registry(|registry| registry.insert(handle, identity));
    handle
}

/// Run `f` against a registered identity.
pub fn with_identity<T>(
    handle: IdentityHandle,
    f: impl FnOnce(&mut DeviceIdentity) -> Result<T>,
) -> Result<T> {
    with_registry(|registry| match registry.get_mut(&handle) {
        Some(identity) => f(identity),
        None => Err(VelaError::InvalidParameter(
            "no such identity handle (the vault may have locked)".into(),
        )),
    })
}

/// Forget an identity, wiping its keys.
pub fn forget(handle: IdentityHandle) -> bool {
    with_registry(|registry| registry.remove(&handle).is_some())
}

/// Forget every identity — call on lock/sign-out.
pub fn forget_all() {
    with_registry(|registry| registry.clear());
}

/// A fresh 32-byte key for [`DeviceIdentity::seal`], for callers that need one
/// (typically stored in the platform keystore).
pub fn generate_seal_key() -> Zeroizing<[u8; 32]> {
    let mut key = Zeroizing::new([0u8; 32]);
    OsRng.fill_bytes(key.as_mut());
    key
}

#[cfg(test)]
mod tests {
    use super::*;

    const SEAL_KEY: [u8; 32] = [42u8; 32];

    /// The handle registry is process-global, so the tests that clear it must
    /// not run beside the tests that rely on it.
    static REGISTRY: Mutex<()> = Mutex::new(());

    fn registry_guard() -> std::sync::MutexGuard<'static, ()> {
        REGISTRY.lock().unwrap_or_else(|e| e.into_inner())
    }

    #[test]
    fn seal_round_trip_preserves_both_capabilities() {
        let identity = DeviceIdentity::generate().expect("generate");
        let publics = identity.publics().clone();

        let challenge = b"server challenge";
        let signature = identity.sign_auth("device-1", challenge).expect("sign");

        let sealed = identity.seal(&SEAL_KEY).expect("seal");
        let reopened = DeviceIdentity::open(&sealed, &SEAL_KEY).expect("open");

        assert_eq!(reopened.publics(), &publics, "same device after a restart");

        // The signature from before the round trip verifies against the key the
        // reopened identity presents, i.e. it really is the same signing key.
        let vk = signing::HybridVerifyingKey::from_bytes(
            publics.hybrid_vk.as_slice().try_into().expect("vk length"),
        )
        .expect("vk");
        let message = signing::auth_message("device-1", challenge);
        let parsed = signing::HybridSignature::from_bytes(
            signature.as_slice().try_into().expect("sig length"),
        )
        .expect("signature");
        assert!(signing::verify(&vk, &message, &parsed).is_ok());

        // And the share key still opens what was sealed to the public half.
        let ek = kem::HybridPublicKey::from_bytes(&publics.share_ek).expect("ek");
        let capsule = kem::seal_share(&ek, b"shared item").expect("seal share");
        assert_eq!(reopened.open_share(&capsule).expect("open share"), b"shared item");
    }

    #[test]
    fn a_sealed_identity_is_useless_without_the_key() {
        let identity = DeviceIdentity::generate().expect("generate");
        let sealed = identity.seal(&SEAL_KEY).expect("seal");

        assert!(DeviceIdentity::open(&sealed, &[7u8; 32]).is_err());

        // Flipping a byte must fail the AEAD tag rather than yield a mangled key.
        let mut tampered = sealed.clone();
        let last = tampered.len() - 1;
        tampered[last] ^= 1;
        assert!(DeviceIdentity::open(&tampered, &SEAL_KEY).is_err());

        assert!(DeviceIdentity::open(&sealed[..10], &SEAL_KEY).is_err());
    }

    /// The blob the app persists must not contain recognisable key material —
    /// that is the whole point of sealing it rather than storing base64.
    #[test]
    fn the_sealed_blob_exposes_no_key_bytes() {
        let identity = DeviceIdentity::generate().expect("generate");
        let sealed = identity.seal(&SEAL_KEY).expect("seal");

        let signing_bytes = identity.signing_sk.to_bytes();
        let share_bytes = identity.share_dk.to_bytes();
        for secret in [signing_bytes.as_slice(), share_bytes.as_slice()] {
            let window = &secret[..32.min(secret.len())];
            assert!(
                !sealed.windows(window.len()).any(|w| w == window),
                "key material appears verbatim in the sealed blob"
            );
        }
    }

    #[test]
    fn imported_key_material_keeps_working() {
        let original = DeviceIdentity::generate().expect("generate");
        let signing_bytes = original.signing_sk.to_bytes();
        let share_bytes = original.share_dk.to_bytes();

        // What migration off the plaintext store does.
        let imported = DeviceIdentity::import(
            &signing_bytes,
            Some(&share_bytes),
            Some(&original.publics().hybrid_ek),
        )
        .expect("import");

        assert_eq!(imported.publics(), original.publics());

        // What enrollment does: only the signing key travels in the code.
        let enrolled = DeviceIdentity::import(&signing_bytes, None, None).expect("import");
        assert_eq!(enrolled.publics().hybrid_vk, original.publics().hybrid_vk);
        assert_ne!(
            enrolled.publics().share_ek,
            original.publics().share_ek,
            "a missing share key is generated, not left empty"
        );
    }

    #[test]
    fn rotating_the_share_key_changes_what_opens_shares() {
        let mut identity = DeviceIdentity::generate().expect("generate");
        let old_ek = kem::HybridPublicKey::from_bytes(&identity.publics().share_ek).expect("ek");
        let to_old = kem::seal_share(&old_ek, b"before").expect("seal");

        let new_ek_bytes = identity.rotate_share_key();
        assert_ne!(new_ek_bytes, old_ek.to_bytes());

        let new_ek = kem::HybridPublicKey::from_bytes(&new_ek_bytes).expect("ek");
        let to_new = kem::seal_share(&new_ek, b"after").expect("seal");

        assert_eq!(identity.open_share(&to_new).expect("open"), b"after");
        assert!(
            identity.open_share(&to_old).is_err(),
            "the retired key is gone, not kept around"
        );
    }

    #[test]
    fn handles_hand_out_use_but_not_key_material() {
        let _guard = registry_guard();
        let identity = DeviceIdentity::generate().expect("generate");
        let vk = identity.publics().hybrid_vk.clone();
        let handle = register(identity);

        let signature = with_identity(handle, |identity| {
            identity.sign_auth("device-1", b"challenge")
        })
        .expect("sign through the handle");
        assert!(!signature.is_empty());
        assert!(!vk.is_empty());

        assert!(forget(handle));
        assert!(!forget(handle), "forgetting twice is not an error path");
        assert!(
            with_identity(handle, |_| Ok(())).is_err(),
            "a forgotten handle cannot sign again"
        );
    }

    #[test]
    fn forget_all_drops_every_identity() {
        let _guard = registry_guard();
        let a = register(DeviceIdentity::generate().expect("generate"));
        let b = register(DeviceIdentity::generate().expect("generate"));
        assert_ne!(a, b, "handles are distinct");

        forget_all();

        assert!(with_identity(a, |_| Ok(())).is_err());
        assert!(with_identity(b, |_| Ok(())).is_err());
    }
}
